### ISSUE TITLE
 Media (MIME) type for COG

### ISSUE THREAD

**Issue by joanma747** [opengeospatial/CloudOptimizedGeoTIFF#1]
This issue in the GeoTIFF repo discusses about possible COG Media type: https://github.com/opengeospatial/geotiff/issues/34

In summary, there is no way that we can add a parameter in a existing MIME type (IANA does not accept that). Instead, the alternative is to register TIFF again with more parameters.

Currently we have only the application parameter. It seems useful to reserve it for "GeoTIFF". This way, any client supporting  GeoTIFF will support COGs as "simple" GeoTIFFs.

The "Negotiation by profile" (https://www.w3.org/TR/dx-prof-conneg/) spec suggest the addition of the "profile=" parameter to all previous media types or to use "Content-Profile" as part of the media type negotiation.

Content-Profile: http://example.org/profile/x
(profiles could be defined in the OGC NA or else)
Content-Profile: http://www.ogc.org/profile/tiff/cog  or similar

**Comment by EmDevys** [comment]
Another potential option could be image/tiff; application=geotiff+cog

**Comment by cholmes** [comment]
+1 for using the profile, instead of a different application than geotiff, so that clients who just want any geotiff don't have to look for two application types.

**Comment by joanma747** [comment]
Ok. @m-mohr reported that some are already using:
image/tiff; application=geotiff; profile=cloud-optimized 

So my proposal will be to accept that in 2 flavours:
1.-
The originally proposed: image/tiff; application=geotiff; profile=cloud-optimized 

2.- 
Another one when content negotiation is possible and that is more respectful with IANA: that does not defined "profile=" in tiff:
`Content-Type: image/tiff; application=geotiff`
`Content-Profile: http://www.opengis.net/def/profile/geotiff/cloud-optimized`

I hope that is acceptable for anybody.

**Comment by joanma747** [comment]
Nobody has complained about this decision for a while, so I'm closing this issue
