### ISSUE TITLE
Missing requirement about optimized layout of sections

### ISSUE THREAD

**Issue by rouault** [opengeospatial/CloudOptimizedGeoTIFF#2]
As far as I can see, there's no requirement saying that the IFD descriptors should be grouped together at the beginning of the file, with tile byte count and offset arrays then, and finally imagery data. This is important to decrease the number of GET requests

https://gdal.org/drivers/raster/cog.html#low-level could be used for inspiration (the part with the "ghost area" could be left aside as it is perhaps a bit too GDAL specific)

**Comment by joanma747** [comment]
I remember reading about this before. You might be right about this. Please note that the IFD descriptions are ordered with the most detailed first while the imagery data is less detailed first. I wonder if this last aspect is important.

I wonder if this would be a requirement or a recommendation. For the moment let's try a requirement:

In a COG file the The header of the file SHALL point to the IFD of the full resolution image(s), followed by the IFD of the first (largest in dimensions) overview, ... IFD of the last (smallest) overview. After that TileOffsets and TileByteCounts arrays of the above IFDs SHALL follow. Finally, the tile data of the smallest overview , ... the tile data of the first largest overview and data of the full resolution image(s) the SHALL follow.

There are also mentions of "masks" that I'm not sure if are relevant here. I suppose they are.

**Comment by joanma747** [comment]
WE decided in the members meeting that IFD will go first and TileOffset later as a requirement. 

A recommendation will mention:
```
tile data of the smallest overview, if present (with each tile followed by the corresponding tile of mask data, if present), with leader and trailer bytes
…
tile data of the largest overview, if present (interleaved with mask data if present)
tile data of the full resolution image, if present (interleaved with corresponding mask data if present)
```

WE will have a note on possible 2D ordering of tiles using Hilbert or else (as mentions in 19123

**Comment by joanma747** [comment]
Added a recommendation called /rec/rec-class-geotiff/ifd-order
