### ISSUE TITLE
Motivation of the IFD order recommandation

### ISSUE THREAD

**Issue by gcebelieu** [opengeospatial/CloudOptimizedGeoTIFF#26]
(This issue comes from DGIWG Imagery and Gridded Data Panel review of COG Draft Standard - September 2022)

Recommandation 3 ("/rec/rec-class-geotiff/ifd-order") is suggesting to organize data in an certain order when there are several IFD (including mask data IFD) and tiles inside a COG File, in function of the resolutions of the related images.

This is certainly motivated by performance optimization issues, but the standard doesn't explain them. A paragraph that explains the motivation of this recommandation would be helpful.

**Comment by joanma747** [comment]
I copied this from GDAL. I suspected about performance reasons but I do not know exactly why. I have added the following sentence:

"To increase performance, the IFD should be arranged in a particular order expressed in the following recommendation"

If you know more details and you want me to add them in the standard, please supply a text or a reasoning

**Comment by geospatial-jeff** [comment]
It is a performance optimization that allows readers to fetch the entire TIFF header (including all IFDs for all subfiles) in a single HTTP GET Range request upon opening the file for the first time.  This reduces the number of round trips to the server required to read a file and improves cache-ability of the TIFF header for repeat requests to the same image.

The TIFF spec is very flexible with how IFDs are positioned, the only requirement is that the last 4 bytes of the IFD point to the byte offset of the next.  So it is totally valid TIFF to have an image where the source image IFD is at the start of the file, the IFD of the first overview is at the end of the file, and the IFD of the second overview is at the middle of the file.  Reading the header of this image in one HTTP request would require downloading the entire file (defeating the purpose of COG to begin with) or in 3 consecutive HTTP requests.

**Comment by joanma747** [comment]
Thanks for the nice text. I have accommodated most of it in the standard draft. I believe we can close this issue now.
