### ISSUE TITLE
Missing requirement about PlanarConfiguration=Contig ?

### ISSUE THREAD

**Issue by rouault** [opengeospatial/CloudOptimizedGeoTIFF#3]
Until now, the COG definition as used by GDAL is based on PlanarConfiguration=Contig (see https://gdal.org/drivers/raster/cog.html#high-level).
We should perhaps add a requirement for that for now, and potentially remove it in a future version if we want to allow PlanarConfiguration=Separate. One limitation for example with PlanarConfiguration=Contig is that you can't use JPEG compression with 5 or more bands.

**Comment by joanma747** [comment]
Interesting. This takes me by surprise. I do not remember reading anything about this in the COG "literature" that I have checked. I'm not spotting anything in the URL you provided. 
IMHO, it really depends on what you are doing. 
  * If the COG represents an RGB visualization it makes sense to have PlanarConfiguration=Contig 
  * If you are including all band on a Landsat in a single COG file, the common thing to do is extract and show a few band but rarely all of them so PlanarConfiguration=Separate seems more appropriate.

So this looks like a recommendation to me but I will not be initially in favor of requirement.

BTW, for the rest of the readers let me clarify that the original TIFF documentations talks about 1 =  Chunky format (your "contig") and 2 =  Planar format (your "separate"). I rather prefer "your" naming that is far more intuitive.

1 =  Chunky format. The component values for each pixel are stored contiguously. For example, for RGB data, the data is stored as RGBRGBRGB…
2 =  Planar format. The components are stored in separate “component planes.”  For example, RGB data is stored with the Red components in one component plane, the Green in another, and the Blue in another.

Note extracted from the TIFF 6.0
PlanarConfiguration=2 is not currently (_currently means year 1992!_) in widespread use and it is not recommended for general interchange. It is used as an extension and Baseline TIFF readers are not required to support it.

**Comment by joanma747** [comment]
In the Members Meeting we decided that we will leave this as guidance and not as req or rec.
