### ISSUE TITLE
Two minor editorial suggestions

### ISSUE THREAD

**Issue by desruisseaux** [opengeospatial/CloudOptimizedGeoTIFF#30]
## §6. Overview
In the following sentence: _"legacy software will not be able to take advantage of the streaming (…) capabilities"_, I suggest to replace _"will"_ by _"may"_. The reason is that a software does not need to be COG-aware for doing some partial downloads, because tiling is part of TIFF specification. What the software may miss is the use of overviews.

## §7.1.2. Tiles
The following sentence is not quite right: _"Actually, with strips all data from the previous rows needs to be read to get to the following rows."_ Strips are like tiles spanning the full image width. I suggest to replace by something like this: _"Strips divide the content of an image vertically (rows) but not horizontally (columns). With tiling, a much quicker access to a certain area is possible in **both dimensions** (…snip…)"_ (bold characters are addition to current text).

**Comment by joanma747** [comment]
Suggested edits applied
