### ISSUE TITLE
Conformance Class HTTP range dependencies

### ISSUE THREAD

**Issue by tschaub** [opengeospatial/CloudOptimizedGeoTIFF#32]
It looks like the [HTTP Range Conformance Class](http://docs.ogc.org/DRAFTS/21-026.html#http-range-requirements-class) doesn't have a dependency on any of the other COG conformance classes (depending only on the GeoTIFF spec).  Does this mean that any GeoTIFF behind an HTTP(S) service (that accepts range requests) is cloud optimized?

**Comment by geospatial-jeff** [comment]
It shouldn't, COGs rely on tiles over strips ([7.1.2](http://docs.ogc.org/DRAFTS/21-026.html#_tiles)) and the ordering of IFDs ([7.2.1](http://docs.ogc.org/DRAFTS/21-026.html#_requirement_reduced_resolution_subfiles)) to be range request friendly.  A GeoTiff which doesn't implement these may be range request friendly but it isn't guaranteed.

**Comment by geospatial-jeff** [comment]
Ordering all tiles of the same row in the COG across consecutive byte ranges also makes a COG more range-request friendly because all of the tiles across a single row may be requested with a single range request.  I don't see a conformance class for this though.

See the `GDAL_HTTP_MERGE_CONSECUTIVE_RANGES` config option (https://developmentseed.org/titiler/advanced/performance_tuning/#gdal_http_merge_consecutive_ranges)

**Comment by tschaub** [comment]
My point was that the [**HTTP Range Conformance Class**](http://docs.ogc.org/DRAFTS/21-026.html#http-range-requirements-class) (http://www.opengis.net/spec/COG/1.0/req/req-class-http-range) doesn't currently depend on the [**GeoTIFF Tiles Conformance Class**](http://docs.ogc.org/DRAFTS/21-026.html#geotiff-format-requirements-class) (http://www.opengis.net/spec/COG/1.0/req/req-class-geotiff-format).

These are the current dependencies of the **HTTP Range Conformance Class**: https://github.com/opengeospatial/CloudOptimizedGeoTIFF/blob/79589f39d0d9df68d6cd8adfb93159ef6cb245cc/standard/requirements/requirements_httprange.adoc#L3-L11

In addition, the spec says an implementation only needs to conform with one or more of the conformance classes.  See: https://github.com/opengeospatial/CloudOptimizedGeoTIFF/blob/79589f39d0d9df68d6cd8adfb93159ef6cb245cc/standard/clause_2_conformance.adoc#L22-L23

As written, the draft spec implies that an implementation could only conform with the **HTTP Range Conformance Class** to be a Cloud Optimized GeoTIFF.

I'm not referring to the de facto [COG spec](https://github.com/cogeotiff/cog-spec/blob/master/spec.md), just the current draft OGC spec.

@joanma747 - would you accept a pull request that added the **GeoTIFF Tiles Conformance Class** as a dependency of the **HTTP Range Conformance Class**, or is it intentional that satisfying only the **HTTP Range** requirements implies conformance with the OGC spec?

Curious to hear @rouault's thoughts as well.  Should tiled layout always be required or only with GeoTIFFs of a certain size (as enforced by [`validate_cloud_optimized_geotiff.py`](https://github.com/OSGeo/gdal/blob/master/swig/python/gdal-utils/osgeo_utils/samples/validate_cloud_optimized_geotiff.py))?

**Comment by rouault** [comment]
> As written, the draft spec implies that an implementation could only conform with the **HTTP Range Conformance Class** to be an OGC Cloud Optimized GeoTIFF.

That wouldn't make sense to me. The HTTP range conformance class should likely have the "GeoTIFF Tiles Conformance Class" (probably that one would be better name "COG file layout conformance class" or something like that) as a dependency.

> Should tiled layout always be required or only with GeoTIFFs of a certain size (as enforced by [validate_cloud_optimized_geotiff.py](https://github.com/OSGeo/gdal/blob/master/swig/python/gdal-utils/osgeo_utils/samples/validate_cloud_optimized_geotiff.py))?

I guess the current state of the validate_cloud_optimized_geotiff.py script was written with the thought that COG optimization only makes sense (= brings values) for large enough files. For small enough files (smaller than a tile size typically), any valid GeoTIFF will be "optimized", and I didn't want to annoy people with pedantic warnings without practical consequences (that said the script verifies that the metadata is before data, so it doesn't follow that simple logic) Well, that assumes that people use generic GeoTIFF readers to read COG, and not COG only which would work only with tiled GeoTIFFs and not stripped GeoTIFFs.

Two possible actions:
- an extra requirement is added to the COG spec "Independently of other requirements, any valid GeoTIFF file whose ImageWidth <= 512 and ImageHeight <= 512 is considered as a valid COG file"
- or the validation script is changed to require tiling even for such small files. Actually, just seeing that the GDAL COG driver generates tiled dataset even for files smaller than a tile size, I'd be inclined to this option.

**Comment by geospatial-jeff** [comment]
> or the validation script is changed to require tiling even for such small files. Actually, just seeing that the GDAL COG driver generates tiled dataset even for files smaller than a tile size, I'd be inclined to this option.

Yes, allowing COGs to be either tiled or stripped (if small enough) is bad for interoperability and makes COG native readers/writes more complex than they need to be.  There is no precedence for this distinction in other cloud-optimized, tile-based formats like zarr/tiledb etc. (which are tiled no matter how big or small the dataset is).

**Comment by joanma747** [comment]
The reason why httprange does not depend on any other conformance class was that the target is different from the other classes (that target a so called "TIFF Encoder"). In practice it makes no sense to impose to a "web server" conditions on a file format.

However, I understand this creates the paradox that @tschaub explained at the beginning. In addition, it does not make any sense to have a req. class that imposes http range an nothing else. This is not related to COG and it is what what [rfc7233](https://datatracker.ietf.org/doc/html/rfc7233) does already.

I think, the solution is to add a requirement or a sub-requirement requesting the web server to support serving the COG format and then make "httprange" to depend on "format" (core). 

I'll do this modification now. I hope that fixes the issue.

**Comment by joanma747** [comment]
BTW, I have replaced rfc7233 by the new: https://www.rfc-editor.org/rfc/rfc9110#name-range-requests
