### ISSUE TITLE
We need three submitting organizations

### ISSUE THREAD

**Issue by joanma747** [opengeospatial/CloudOptimizedGeoTIFF#4]
In the current draft of the standard there is only one submitting organization. A OGC standard requires 3 submitting organizations. Please help us and, if you are interested in becoming a submitting organization let us know.

**Comment by joanma747** [comment]
> Planet Labs PBC is interested in becoming a submitting organization!
Great! Thanks

Anyone else?

**Comment by vincentsarago** [comment]
I see @rouault opened #9 to add **Spatialys** but if we need more, **Development Seed** will be happy to be part of this.

**Comment by joanma747** [comment]
Thanks everybody for your willingness to support this document
